# Generated by Django 3.2.3 on 2021-08-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210811_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=6,on_delete=django.db.models.deletion.CASCADE, to='auctions.itemcategory'),
        ),
    ]
