# Generated by Django 3.2.3 on 2021-08-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='listed_by',
        ),
    ]
