# Generated by Django 3.2.3 on 2021-08-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_user_listing_listed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_items', to='auctions.user', default=1),
        ),
    ]
