# Generated by Django 3.2.3 on 2021-09-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_win_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default='Other', on_delete=django.db.models.deletion.CASCADE, related_name='listing_items', to='auctions.itemcategory'),
        ),
    ]
